export const ACTION_TYPES = {
  SET_NORMALISED_ARRAY_DATA: "@@namespace/SET_NORMALISED_ARRAY_DATA",
  SET_NORMALISED_OBJECT_DATA: "@@namespace/SET_NORMALISED_OBJECT_DATA",
  SET_PRIMITIVE_DATA: "@@namespace/SET_PRIMITIVE_DATA",
  SET_STATE_WITH_LOADER: "@@namespace/SET_STATE_WITH_LOADER",
};
export const ACTION_TYPE_SUFFIXES = {
  SUCCESS: "_SUCCESS",
  FAIL: "_FAIL",
  RESET: "_RESET",
};
